spring.application.name=demo

server.port=8081

spring.data.mongodb.uri=mongodb+srv://kiwi:Jk35338072@cluster0.brk12j0.mongodb.net/Final_Project?retryWrites=true&w=majority&connectTimeoutMS=10000&socketTimeoutMS=10000
spring.data.mongodb.database=Final_Project

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=multimediafinalproject03@gmail.com
spring.mail.password=qqkphedlkfhuslyl
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.debug=true

imgur.client-id = 59f0ad727c03806
imgur.client-secret = 6619af3b3a29b70df65acf329549b980b3976d47

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG
